openapi: 3.0.3
info:
  title: Calculadora API
  description: API de ejemplo para realizar operaciones aritméticas (POC)
  version: 1.0.0
paths:
  /calculator/operate:
    post:
      summary: Perform a calculation
      operationId: calculate
      description: Receives two numbers and an operation type to perform and returns the result of the operation.	  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OperationRequest'
              example:
                a: 5.0
                b: 3.0
                operation: "add"
      responses:
        "200":
          description: Result of the sum
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
        "400":
          description: Incorrect request

components:
  schemas:
    OperationRequest:
      type: object
      properties:
        operation:
          type: string
          description: "The operation to perform (e.g. add, subtract)"
          example: "add"
        number1:
          type: number
          format: double
          example: 10
        number2:
          type: number
          format: double
          example: 5
      required:
        - number1
        - number2
    OperationResponse:
      type: object
      properties:
        result:
          type: number
          format: double
          example: 15
      required:
        - result
